language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-marionetteify' ]; then cd .. && eval "mv $currentfolder generator-marionetteify" && cd generator-marionetteify; fi

